spring:
  application:
    name: ai-service
  config:
    import: optional:configserver:http://localhost:8888

#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
#      group-id: activity-processor-group
#      properties:
#        spring.json.use.type.headers: false
#        spring.json.value.default.type:
#        spring.json.trusted.packages: "*"
#
#gemini:
#  api:
#    url: ${GEMINI_URL}
#    key: ${GEMINI_KEY}
#
#kafka:
#  topic:
#    name: activity-events
#
#  data:
#    mongodb:
#      uri: mongodb://Localhost:27017/airecommendationfitness
#      database: airecommendationfitness
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#
#server:
#  port: 8083