spring:
  data:
    mongodb:
      uri: mongodb+srv://pranjay_db:8iMODRP72u5aYo0F@cluster0.vvgl0tv.mongodb.net/fitness-activity
      database: fitness-activity
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializerkafka:
  topic:
    name: activity-events

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: ${PORT:8082}

